[package]
name = "pok-8-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "^0.7.3"
bencher = "0.1.5"


[[bench]]
name = "emu_bcd"
harness = false